name: seafood_crossing
description: A new Flutter project.

version: 1.2.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cached_network_image: ^2.0.0
  cupertino_icons: ^0.1.3
  device_info: ^0.4.2+1
  dio: ^3.0.9
  flutter_sticky_header: ^0.4.2
  package_info: ^0.4.0+16
  shared_preferences: ^0.5.6+3
  unicorndial: ^1.1.5
  url_launcher: ^5.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4

flutter:
  uses-material-design: true

flutter_icons:
  ios: true
  android: true
  image_path: "assets/icon/icon.jpg"
